org.gradle.jvmargs=-Xmx512m -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=64m -XX:+HeapDumpOnOutOfMemoryError -Xss256k -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.daemon=false
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
